dataset: mot_crowdhuman

crowdhuman_train_split: train_val
train_split: mot20_train_coco
val_split: mot20_train_cross_val_frame_0_5_to_1_0_coco

mot_path_train: data/MOT20
mot_path_val: data/MOT20

resume: models/crowdhuman_deformable_trackformer/checkpoint_epoch_80.pth

epochs: 50
lr_drop: 10